version: "3.8"

services:
  docusaurus:
    image: smartbrotha/docusaurus-v3-synology:v1.0
    container_name: docusaurus
    init: true
    restart: always
    expose:
        - 3000
        - 35729
    ports:
      - "3000:3000"
      - "35729:35729"
      
    volumes:
      - /volume1/docker/docusaurus/my-website/blog:/app/docusaurus/blog
      - /volume1/docker/docusaurus/my-website/docs:/app/docusaurus/docs
      - /volume1/docker/docusaurus/my-website/src:/app/docusaurus/src
      - /volume1/docker/docusaurus/my-website/static:/app/docusaurus/static
      - /volume1/docker/docusaurus/my-website/README.md:/app/docusaurus/README.md
      - /volume1/docker/docusaurus/my-website/sidebars.js:/app/docusaurus/sidebars.js
      - /volume1/docker/docusaurus/my-website/docusaurus.config.js/app/docusaurus/docusaurus.config.js
      


    working_dir: /app/docusaurus

    entrypoint: ["/app/docusaurus/start.sh"]
